### ISSUE TITLE
How to use command line for on2json file?

### ISSUE THREAD

**Issue by shaibearary** [orbingol/rw3dm#10]
I just type on2json MyONFile.3dm extract_curves=True in example(change it with my own filename)

it says on2json is not command line

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by orbingol** [comment]
I really hate to say but it works perfectly for me. I don't have a Mac, so I am not sure if it works on Mac but Windows, Linux (I have tested several distros) work fine. You might need to return back to the basics here, such as opening a command prompt/terminal instance on the directory you downloaded. You can also change the installation directory while you are configuring CMake (using the GUI version might be a good idea here)

I am closing this issue as I don't see it as an enhancement or a bug. Please use nurbs-python@googlegroups.com email list if you have questions.
