### ISSUE TITLE
on2json/json2on: command not found

### ISSUE THREAD

**Issue by UgurOzcanFited** [orbingol/rw3dm#16]
When I applied the instructions, I am getting "command not found"  on the terminal. Is there any missing point(s) on my side? I am not sure. What should I do?

![Screenshot from 2021-07-02 14-32-39](https://user-images.githubusercontent.com/51903462/124276629-bd02b200-db4c-11eb-8574-63a74a3cdeaf.png)

**Configuration:**
 - Operating system: Ubuntu 20.04
 - CMake version:  3.16.3

**Comment by orbingol** [comment]
Try `./json2on` or `./on2json`.

Details: https://askubuntu.com/questions/320632/why-do-i-need-to-type-before-executing-a-program-in-the-current-directory
