### ISSUE TITLE
on2json: Failed to convert solid CAD models to JSON

### ISSUE THREAD

**Issue by pimakshay** [orbingol/rw3dm#9]
I tried to extract the surface control points of a solid model using the on2json executable, but the operation failed. After analysing the case, I found that rw3dm does not support converting solid models; instead, the same object is constructed using the NURBS surfaces and joined to form a solid will work fine. 
Note: By solid model, I mean, cad models created by extruding from a curve etc.

[bug.zip](https://github.com/orbingol/rw3dm/files/4184724/bug.zip)

Steps to reproduce the behaviour:
1. I am attaching a sample .3DM file of a cuboid body.
2. Run the on2json executable to extract only the surfaces: on2json cuboid.3dm extract_curves=false;
3. The error screenshot is attached.

**Comment by orbingol** [comment]
@pimakshay Sorry for my late response.

I have pinpointed the issue. rw3dm determines the type of input using `object_type` enum defined in `opennurbs_defines.h` file. This file comes with OpenNURBS and provides the object types, such as surface, curve, volume, etc. The file `cuboid.3dm` contains an object with the type `ON_Extrusion` as you explained in your note.

I will add the option to extract data from extruded objects and release it in a few days.

**Comment by orbingol** [comment]
This issue is fixed on the `devmaster` branch. Here is a sample output generated from `cuboid.3dm`:

![image](https://user-images.githubusercontent.com/5276943/80303057-bc110c00-8762-11ea-8eed-18187bc92dbe.png)
